version: 0.1
phases:
  install:
    commands:
    - pip install --upgrade pip
    - pip install aws-xray-sdk -t lambda/historySteamGame/vendored/.
    - pip install aws-xray-sdk -t lambda/steamGame/vendored/.
    - bash lambda/build.sh
artifacts:
  type: zip
  files:
  - sam-output.yaml