version: 0.1
phases:
  install:
    commands:
    - pip install aws-xray-sdk -t lamblda/historySteamGame
    - pip install aws-xray-sdk -t lamblda/steamGame
    - bash lambda/build.sh
artifacts:
  type: zip
  files:
  - sam-output.yaml